spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: movie_application

---
spring:
  config:
    activate:
      on-profile: stage

  data:
    mongodb:
      host: localhost
      port: 27017
      database: movie_info

---
spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      host: localhost
      port: 27017
      database: movie_info